ewc-media-controls (WIP)
QutEcoacoustics/ecoacoustics-web-components pull request #9
Opened 2021-05-17 05:59 UTC by benjaminARowe

## What
Initial version of ewc-media-controls. This component can be applied to any element that extends HTMLMediaElement

## Why
This component adds support for play/pause of HTMLAudioElement and (eventually) ewc-spectrogram, and user configurable back / forward buttons

## How
Using getElementById to get the element associated with the 'for' property on ewc-media-controls, then checking if the element is an instance of HTMLMediaElement. Error's are thrown if the element does not exist or is not an instance of HTMLMediaElement. Warning is logged to console if no element id is provided

## Testing (WIP)
Added unit tests for:
    - Warns and renders if no media source is given
    - Throws an error when the media element does not exist
    - Throws an error when the element is not a HTMLMediaElement
    - Renders if the element is a HTMLMediaElement
    - Renders a back button if onBack is defined
    - Renders a back and forward buttons if onBack and onForward are defined
(WIP) some tests fail if instanceof HTMLMediaElement is used. Currently using a workarround. The following solutions were attempted:
    - Use stencil's built-in mock window (newSpecPage.win)
        - Stencil's implementation of window is incomplete, so this fails
    - Use "jsdom"
        - jsdom is incompatible with stencil in some ways relating to limited support for shadowdom. e.g. querySelector("audio")[0] instanceof HTMLMediaElement -> false
    - Add "allow-unsafe" id to audio for tests
        -   This works, but is a bad solution

2021-05-17 11:28 UTC, atruskie requested changes
- There's a lot of noise in this PR. Try to keep branches clean with just  the relevant changes.
- For example, all the stub definitions would have been better placed in another PR

For the rest of this review, I'm ignoring all definitions other than the media controls. Treat the media controls as a template for which we'll base all the other stubs.

I'm also going to suggest making it standard practice to create an issue describing the work you are going to undertake before you start - to make sure we're on the same page before you start.

Does the current build pipeline support scss/sass compilation? There is a `stencil-sass` plugin?

I didn't see any tests for CSS customisation. Add a test that checks the icons can be replaced by a host style. e.g. `ewc-media-controls::part(pause) { color: red; }` 

The most important part of this PR will be establishing some kind of style guide afterwards.

I'm going to require that you turn on the no global variable access option in your linter.

2021-05-17 11:28 UTC, atruskie commented on src/components/media-controls/media-controls.tsx
> +  @Prop() onForward: VoidFunction;
These should be `@Event`s no? With the type `EventEmitter`?

2021-05-17 11:28 UTC, atruskie commented on src/components/media-controls/media-controls.tsx
> +  @Prop() for: string;
Ok I'm reading the docs, `@prop`s that are not simple types are not output by the compiler. I'd still like to see the same property used for the complex and string types where possible/makes sense.

2021-05-17 11:28 UTC, atruskie commented on src/components/media-controls/media-controls.tsx
> +    }
Overly defensive here?

If not, collapse to null-access operator chain?

2021-05-17 11:28 UTC, atruskie commented on src/components/media-controls/readme.md
> +| `middle` | `middle`  | The middle name | `string` | `undefined` |
Update

2021-05-17 11:28 UTC, atruskie commented on src/utils/media.ts
> +}
This should be a type that extends `Error`.

Also should be namespaced

2021-05-17 11:28 UTC, atruskie commented on src/utils/media.ts
> +  let mediaSource = document.getElementById(element);
global reference here is *not* ok.

Pass in the `<host/>` element and use it's query selector API

2021-05-17 11:28 UTC, atruskie commented on src/utils/media.ts
> +    console.warn('No HTMLMediaElement was defined');
No global access is allowed to `console`. Inject it.

Also every console message generated by this project should be namespaced. Make a global helper service.,

2021-05-17 11:28 UTC, atruskie commented on src/utils/media.ts
> +  else if (mediaSource instanceof window.HTMLMediaElement || mediaSource.id == 'allow-unsafe') {
again no global variable access allowed

2021-06-03 02:50 UTC, Allcharles approved these changes
I don't have a lot to add on top of Anthonys review. Mostly some of the variable names could be improved, and there is some repeated code that could be simplified.

2021-06-03 02:50 UTC, Allcharles commented on src/components/media-controls/media-controls.tsx
> +    }
Just some general code cleanup which could be used through the project

```suggestion
    if (!this.mediaSource) {
      return
    }

    const updateMediaPausedState = () => this.mediaPaused = this.mediaSource.paused;
    this.mediaSource.addEventListener('pause', updateMediaPausedState);
    this.mediaSource.addEventListener('play', updateMediaPausedState);
    updateMediaPausedState();
```

2021-06-03 02:50 UTC, Allcharles commented on src/components/media-controls/media-controls.tsx
> +  @State() mediaPaused: boolean;
Rename this

```suggestion
  @State() isMediaPaused: boolean;
```

2021-06-23 06:55 UTC, merged